### ISSUE TITLE
バージョンアップ時の仕様変更？

### ISSUE THREAD

**Issue by believeitmyway** [AIWolfSharp/AIWolf_NET#1]
AIWolf_NETのバージョンアップを行ったときにうまく動かず困っています。
情報を頂けると幸いです。

【前提】
・AIWolf_NET-0.1.0を用いて開発を実施。
　この環境では正しくサーバへ接続してプレイができることを確認。
・AIWolf_NET-0.2.2へバージョンアップを実施。
　（具体的には、AIWolfLibClient.dll,AIWolfLibCommon.dll,ClientStarter.exeを置き換え）

【事象】
・作成したプロジェクトのデバッグからClientStarter.exeを呼ぶと、プレーヤのインスタンス生成あたり？で何も吐かずに終了してしまう。
・ClientStarter.exeの中で終了している可能性あり？
・タイムアウトを10秒など長めに設定しても現象は変わらず。

【教えて頂きたいこと】
・AIWolf_NET-0.1.0⇒AIWolf_NET-0.2.2へバージョンアップするに当たって、
　何か仕様変更があり、引数やプログラムを書き換える必要はあるのでしょうか？

**Comment by AIWolfSharp** [comment]
もし，Json.NETのバージョン8をお使いでしたら，最新のバージョン9に入れ替えてみてください．
[AIWolf_NET-0.2.2.zip](https://github.com/AIWolfSharp/AIWolf_NET/releases/download/v0.2.2/AIWolf_NET-0.2.2.zip)に同梱されています．

それでも動かなければ，ご連絡ください．

**Comment by believeitmyway** [comment]
ありがとうございます。
Json.NETは更新していませんでした。
試してみます。
